name: label new contributor

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          script: |
            # Add a label when contributor opens an issue or pull request
            if: contains(steps.label-the-PR.outputs.all-labels, 'frontend')
            if (github.event_name=="issue") {
              core.setOutput('label', 'issue');
            }
            if (github.event_name=="pull_request") {
              core.setOutput('label', 'pull request');
            }  
