name: "Pull Request Labeler"
on:
- pull_request_target
- issues
- issue_comment

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: "github context dump"
      run: echo '${{ toJSON(github.event) }}' | jq
      shell: bash
    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.TOKEN_SECRET }}"
        sync-labels: true
        configuration-path: .github/labeler.yml
        dot: true
        pr-number: |
          1
    
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_SECRET }}
        OWNER: ${{ github.event.issue.user.login }}
        REPO: ${{ github.event.repository.name }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
