name: "Pull Request Labeler"

on:
-  pull_request_target

jobs:
  label:
    runs-on: ubuntu latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository:"JulieGunawan/git-action-test"
      - uses: actions/labeler@v4
