name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: "github context dump"
      run: echo '${{ toJSON(github.event) }}' | jq
      shell: bash
      
    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.TOKEN_SECRET }}"
