name: "Pull Request Labeler"
on:
  - issues
  - issue_comment
  - pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: "github context dump"
      run: echo '${{ toJSON(github.event) }}' | jq
      shell: bash
    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.TOKEN_SECRET }}"



      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_SECRET }}
        OWNER: ${{ github.event.issue.user.login }}
        REPO: ${{ github.event.repository.name }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        LABEL: ${{ github.event.issue.labels[0].name }}
