name: label new contributor

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  label:
    runs-on: ["contributor"]
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/labeler@v4
        with:
          repo-token: ${{secrets.TOKEN_SECRET}}
          sync-labels: true
          dot: false
          pr-number: |
            1
