name: label new contributor

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{secrets.TOKEN_SECRET}}
          configuration-path: "git-action-test/.github/workflows/labeler.yml"
          dot: false
          pr-number: |
            1
            2
